/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_learzhu_jniuninstall_JNIUninstall */

#ifndef _Included_com_learzhu_jniuninstall_JNIUninstall
#define _Included_com_learzhu_jniuninstall_JNIUninstall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_learzhu_jniuninstall_JNIUninstall
 * Method:    uninstall
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_learzhu_jniuninstall_JNIUninstall_uninstall
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
