/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_learzhu_jniuninstall_JNITest */

#ifndef _Included_com_learzhu_jniuninstall_JNITest
#define _Included_com_learzhu_jniuninstall_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_learzhu_jniuninstall_JNITest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_learzhu_jniuninstall_JNITest_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_learzhu_jniuninstall_JNITest
 * Method:    testHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_learzhu_jniuninstall_JNITest_testHello
  (JNIEnv *, jobject);

/*
 * Class:     com_learzhu_jniuninstall_JNITest
 * Method:    uninstall
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_learzhu_jniuninstall_JNITest_uninstall
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
